class ChallengesController < ApplicationController
  require 'net/http'
  require 'uri'
  def index
  #   @uri = URI.parse("https://spoonacular-recipe-food-nutrition-v1.p.mashape.com/recipes/random?number=1")
  #   @request = Net::HTTP::Get.new(@uri)
  #   @request["X-Mashape-Key"] = "67QSfPqlNEmshpM6jlpdtEGuN4YJp1HNB1DjsnETnZfKYTb12X"
  #   @request["X-Mashape-Host"] = "spoonacular-recipe-food-nutrition-v1.p.mashape.com"

  #   req_options = {
  #     use_ssl: @uri.scheme == "https",
  #   }

  #   @response = Net::HTTP.start(@uri.hostname, @uri.port, req_options) do |http|
  #     http.request(@request)
  #   end
  # end

  def show
  end

  def new
  end

  # challenge needs:
  # create_table "challenges", force: :cascade do |t|
  #   t.string "location"
  #   t.string "food"
  #   t.datetime "due_by"
  #   t.boolean "complete", default: false
  #   t.integer "groupie_id"
  #   t.datetime "created_at", null: false
  #   t.datetime "updated_at", null: false
  #   t.index ["groupie_id"], name: "index_challenges_on_groupie_id"
  # end

  # Location is randomly generated by geonames api
      #google api needs 
        #lat  --get from group info
        #long  --get from group info
        #responseStyle
        #citySize
        #radius  --get from group info
        #maxRows
        #username
  # Food Generated by Food API
  # Due by now +24hr
  # groupies
   def create
    @groups = Group.all
    @style = 'short'
    @size = 'cities5000'
    @maxRows = '50'
    @username = 'rbsouth'
    @groups.each do |group|
      @radius = group.radius.to_s
      @latitude = group.latitude.to_s
      @longitude = group.longitude.to_s

      # Get random city
      @geonames_api_call = JSON.parse(open("http://api.geonames.org/findNearbyPlaceNameJSON?lat=" + @latitude + "&lng=" + @longitude + "&style=" + @style + "&cities=" + @size + "&radius=" + @radius + "&maxRows=" + @maxRows + "&username=" + @username).read)
      @city = @geonames_api_call["geonames"].sample
      @city_name = @city["name"]
      @city_lat = @city["lat"].to_f
      @city_lng = @city["lng"].to_f

      # Get random food
      @uri = URI.parse("https://spoonacular-recipe-food-nutrition-v1.p.mashape.com/recipes/random?number=1")
      @request = Net::HTTP::Get.new(@uri)
      @request["X-Mashape-Key"] = "67QSfPqlNEmshpM6jlpdtEGuN4YJp1HNB1DjsnETnZfKYTb12X"
      @request["X-Mashape-Host"] = "spoonacular-recipe-food-nutrition-v1.p.mashape.com"

      req_options = {
        use_ssl: @uri.scheme == "https",
      }

      @response = Net::HTTP.start(@uri.hostname, @uri.port, req_options) do |http|
        http.request(@request)
      end
      group.groupies.each do |groupie|
        groupie.challenges.new()
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end
