class ChallengesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  # challenge needs:
  # create_table "challenges", force: :cascade do |t|
  #   t.string "location"
  #   t.string "food"
  #   t.datetime "due_by"
  #   t.boolean "complete", default: false
  #   t.integer "groupie_id"
  #   t.datetime "created_at", null: false
  #   t.datetime "updated_at", null: false
  #   t.index ["groupie_id"], name: "index_challenges_on_groupie_id"
  # end

  # Location is randomly generated by google api
      #google api needs 
        #lat  --get from group info
        #long  --get from group info
        #responseStyle
        #citySize
        #radius  --get from group info
        #maxRows
        #username
  # Food Generated by Food API
  # Due by now +24hr
  # groupies
   def create
    @groups = Group.all
    @style = 'short'
    @size = 'cities15000'
    @maxRows = '50'
    @groups.each do |group|
      @radius = group.radius
      @latitude = group.latitude
      @longitude = group.longitude
      @gmaps_api_call = JSON.parse(open().read)
      Challenge.new()
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
end
